# Generated by Django 5.2 on 2026-05-14 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_accessmodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="e.g. 'soe-governance-2026'", max_length=100, unique=True, verbose_name='slug')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('subtitle', models.TextField(blank=True, verbose_name='subtitle')),
                ('partners', models.CharField(blank=True, max_length=300, verbose_name='partners')),
                ('dates', models.CharField(help_text="e.g. '1 – 4 September 2026'", max_length=100, verbose_name='dates (display string)')),
                ('location', models.CharField(max_length=200, verbose_name='location')),
                ('expires', models.DateField(blank=True, help_text='Banner is hidden on and after this date', null=True, verbose_name='auto-expiry date')),
                ('sectors', models.JSONField(blank=True, default=list, help_text='JSON list e.g. ["Energy", "Finance"]', verbose_name='sectors')),
                ('stats', models.JSONField(blank=True, default=list, help_text='JSON list e.g. [{"n": "3.5", "l": "Intensive Days"}]', verbose_name='stats')),
                ('body', models.TextField(blank=True, verbose_name='body copy')),
                ('facilitator_label', models.CharField(blank=True, default='Lead Facilitator', max_length=100, verbose_name='facilitator label')),
                ('facilitator_name', models.CharField(blank=True, max_length=200, verbose_name='facilitator name')),
                ('facilitator_bio', models.TextField(blank=True, verbose_name='facilitator bio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'upcoming event',
                'verbose_name_plural': 'upcoming events',
                'ordering': ['expires'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'id'], 'verbose_name': 'track / category', 'verbose_name_plural': 'tracks / categories'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['category__order', 'rank_id', 'id'], 'verbose_name': 'course', 'verbose_name_plural': 'courses'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_de',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_fr',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration_de',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration_en',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration_fr',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='author_name_de',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='author_name_en',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='author_name_fr',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='author_title_de',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='author_title_en',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='author_title_fr',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='content_de',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='content_fr',
        ),
        migrations.AddField(
            model_name='category',
            name='badge',
            field=models.CharField(blank=True, help_text="Optional badge text e.g. 'NEW'", max_length=20, verbose_name='badge'),
        ),
        migrations.AddField(
            model_name='category',
            name='bespoke',
            field=models.BooleanField(default=False, help_text='Marks this as the bespoke / in-house track', verbose_name='bespoke track'),
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#C8960C', help_text='Hex colour used for the track tab and cards', max_length=20, verbose_name='accent colour'),
        ),
        migrations.AddField(
            model_name='category',
            name='faculty',
            field=models.CharField(blank=True, help_text='Faculty credit line shown below the track header', max_length=500, verbose_name='faculty line'),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order — lowest first', verbose_name='order'),
        ),
        migrations.AddField(
            model_name='category',
            name='short',
            field=models.CharField(blank=True, help_text="Breadcrumb label e.g. 'Leadership Journey'", max_length=60, verbose_name='short label'),
        ),
        migrations.AddField(
            model_name='course',
            name='audience',
            field=models.TextField(blank=True, verbose_name='who should attend'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, help_text="e.g. 'Advanced', 'Senior Leaders', 'All Leaders'", max_length=100, verbose_name='level'),
        ),
        migrations.AddField(
            model_name='course',
            name='num',
            field=models.CharField(blank=True, help_text="e.g. '01 Leadership Journey' or 'AIM 01'", max_length=100, verbose_name='course number / code'),
        ),
        migrations.AddField(
            model_name='course',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='subtitle'),
        ),
        migrations.AddField(
            model_name='course',
            name='teaser',
            field=models.TextField(blank=True, help_text='~30-word card preview shown in the programme grid', verbose_name='teaser'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text="Full label e.g. 'Track 1: Leadership Journey'", max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.category', verbose_name='track'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(help_text='Full body text shown on the detail page', verbose_name='synopsis'),
        ),
        migrations.AlterField(
            model_name='course',
            name='goals',
            field=models.TextField(blank=True, help_text='Comma-separated goals', null=True, verbose_name='goals'),
        ),
        migrations.AlterField(
            model_name='course',
            name='mode',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='mode'),
        ),
        migrations.AlterField(
            model_name='course',
            name='objectives',
            field=models.TextField(blank=True, help_text='Comma-separated e.g.: Understand X, Develop Y', null=True, verbose_name='objectives'),
        ),
        migrations.AlterField(
            model_name='course',
            name='outlines',
            field=models.TextField(blank=True, help_text='Module:Topic, Module:Topic format', null=True, verbose_name='outlines'),
        ),
        migrations.AlterField(
            model_name='course',
            name='rank_id',
            field=models.IntegerField(blank=True, help_text='Controls display order within the track — lower = first', null=True, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='course',
            name='training_format',
            field=models.CharField(choices=[('Online', 'Online'), ('Classroom', 'Classroom'), ('Executive', 'Executive'), ('Bespoke', 'Bespoke')], default='Online', max_length=150, verbose_name='training format'),
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Short identifier e.g. 'aim', 'asme', 'ofc'", verbose_name='slug')),
                ('label', models.CharField(help_text="Display name e.g. 'Asset Integrity Management'", max_length=100, verbose_name='label')),
                ('color', models.CharField(blank=True, help_text='Override hex colour; falls back to the track colour', max_length=20, verbose_name='colour')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='core.category', verbose_name='track')),
            ],
            options={
                'verbose_name': 'cluster / sub-track',
                'verbose_name_plural': 'clusters / sub-tracks',
                'ordering': ['order', 'id'],
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='core.cluster', verbose_name='cluster'),
        ),
    ]
