# Generated by Django 5.2 on 2026-05-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_upcomingevent_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=100, verbose_name='page')),
                ('block', models.CharField(max_length=150, verbose_name='block')),
                ('content_en', models.TextField(blank=True, verbose_name='content (English)')),
                ('content_de', models.TextField(blank=True, verbose_name='content (German)')),
                ('is_rich_text', models.BooleanField(default=False, verbose_name='rich text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'static content block',
                'verbose_name_plural': 'static content blocks',
                'ordering': ['page', 'block'],
                'constraints': [models.UniqueConstraint(fields=('page', 'block'), name='unique_static_content_block')],
            },
        ),
    ]
